// @ts-nocheck  (the bundle below is the bot's plain-JS modules, verbatim; tests cover it)
// pretrade / trade-plan — self-contained x402 Cloud handler (Request → Response)
// Runs the caller's exact trade size on the live Robinhood Chain Uniswap v4 pool (eth_call with a state override,
// nothing is sent) plus a $1 reference in the same block, and returns GO / CAUTION / NO_GO, the measured price
// impact, the expected output, a slippage setting and the amountOutMinimum to use.
const RPC_URL = "https://rpc.mainnet.chain.robinhood.com";
const DISCLAIMER = "Simulated on one block of the live pool. Re-quote right before sending. Not financial advice.";
const bad = (status: number, error: string, hint?: string) => Response.json({ error, hint }, { status }); // >= 400: not charged
async function http(url: string, body?: unknown) {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), 8000);
  try {
    const r = await fetch(url, body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body), signal: ctrl.signal } : { headers: { accept: "application/json" }, signal: ctrl.signal });
    const text = await r.text();
    let json = null; try { json = JSON.parse(text); } catch {}
    return { ok: r.ok, status: r.status, json, text };
  } catch (e) { return { ok: false, status: 0, json: null, text: String(e) }; } finally { clearTimeout(t); }
}

// ── BEGIN bundle ── (generated by scripts/bundle-x402.mjs from bot/v4hooks.mjs, bot/sim-runtime.mjs, bot/sim.mjs; do not edit)
const __v4hooks = (() => {
// Uniswap v4 hook inspection. Every musepad launch trades in a v4 pool, and a v4 pool can carry a "hook":
// arbitrary code that runs inside every swap. A malicious hook can quote one price and settle another.
// What a hook is ALLOWED to do is encoded in the low 14 bits of its address, so reading it is free and exact.
// Everything here is read-only chain data: the pool key comes from the PoolManager's Initialize event and is
// verified by re-hashing it into the pool id, so a spoofed event from another contract cannot fake a key.
// Zero dependencies.

// ───────────── keccak256 (pure JS, only a handful of hashes per check, so BigInt lanes are fast enough) ─────────────
const RC = [
  0x0000000000000001n, 0x0000000000008082n, 0x800000000000808an, 0x8000000080008000n, 0x000000000000808bn, 0x0000000080000001n,
  0x8000000080008081n, 0x8000000000008009n, 0x000000000000008an, 0x0000000000000088n, 0x0000000080008009n, 0x000000008000000an,
  0x000000008000808bn, 0x800000000000008bn, 0x8000000000008089n, 0x8000000000008003n, 0x8000000000008002n, 0x8000000000000080n,
  0x000000000000800an, 0x800000008000000an, 0x8000000080008081n, 0x8000000000008080n, 0x0000000080000001n, 0x8000000080008008n,
];
const ROT = [0, 1, 62, 28, 27, 36, 44, 6, 55, 20, 3, 10, 43, 25, 39, 41, 45, 15, 21, 8, 18, 2, 61, 56, 14];
const M64 = (1n << 64n) - 1n;
const rotl = (x, r) => (r === 0 ? x : ((x << BigInt(r)) | (x >> BigInt(64 - r))) & M64);

function keccakF(s) {
  for (let round = 0; round < 24; round++) {
    const c = [0, 1, 2, 3, 4].map((x) => s[x] ^ s[x + 5] ^ s[x + 10] ^ s[x + 15] ^ s[x + 20]);
    for (let x = 0; x < 5; x++) { const d = c[(x + 4) % 5] ^ rotl(c[(x + 1) % 5], 1); for (let y = 0; y < 25; y += 5) s[y + x] ^= d; }
    const b = new Array(25);
    for (let x = 0; x < 5; x++) for (let y = 0; y < 5; y++) b[y + 5 * ((2 * x + 3 * y) % 5)] = rotl(s[x + 5 * y], ROT[x + 5 * y]);
    for (let x = 0; x < 5; x++) for (let y = 0; y < 25; y += 5) s[y + x] = b[y + x] ^ (~b[y + ((x + 1) % 5)] & M64 & b[y + ((x + 2) % 5)]);
    s[0] ^= RC[round];
  }
}

/** keccak256 of a Uint8Array, as 0x-hex. */
function keccak256(bytes) {
  const rate = 136;
  const padded = new Uint8Array(Math.ceil((bytes.length + 1) / rate) * rate);
  padded.set(bytes);
  padded[bytes.length] ^= 0x01;
  padded[padded.length - 1] ^= 0x80;
  const s = new Array(25).fill(0n);
  for (let off = 0; off < padded.length; off += rate) {
    for (let i = 0; i < rate / 8; i++) {
      let lane = 0n;
      for (let k = 7; k >= 0; k--) lane = (lane << 8n) | BigInt(padded[off + i * 8 + k]);
      s[i] ^= lane;
    }
    keccakF(s);
  }
  let out = "0x";
  for (let i = 0; i < 4; i++) for (let k = 0; k < 8; k++) out += Number((s[i] >> BigInt(8 * k)) & 0xffn).toString(16).padStart(2, "0");
  return out;
}
const utf8 = (t) => new TextEncoder().encode(t);
const hexBytes = (h) => Uint8Array.from((h.replace(/^0x/, "").match(/../g) ?? []).map((b) => parseInt(b, 16)));

// ───────────── v4 constants, straight from v4-core (Hooks.sol, LPFeeLibrary.sol, PoolManager events) ─────────────
const INIT_TOPIC = keccak256(utf8("Initialize(bytes32,address,address,uint24,int24,address,uint160,int24)"));
const DYNAMIC_FEE = 0x800000;
const ZERO = "0x0000000000000000000000000000000000000000";

/** bit → permission, from Hooks.sol. "delta" permissions let the hook change how much the swapper gets. */
const PERMISSIONS = [
  [13, "beforeInitialize"], [12, "afterInitialize"],
  [11, "beforeAddLiquidity"], [10, "afterAddLiquidity"], [9, "beforeRemoveLiquidity"], [8, "afterRemoveLiquidity"],
  [7, "beforeSwap"], [6, "afterSwap"], [5, "beforeDonate"], [4, "afterDonate"],
  [3, "beforeSwapReturnsDelta"], [2, "afterSwapReturnsDelta"], [1, "afterAddLiquidityReturnsDelta"], [0, "afterRemoveLiquidityReturnsDelta"],
];
function permissionsOf(hook) {
  const bits = Number(BigInt(hook) & 0x3fffn);
  return PERMISSIONS.filter(([b]) => bits & (1 << b)).map(([, name]) => name);
}

// EIP-1967 slots and the EIP-1167 clone prefix
const IMPL_SLOT = "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc";
const BEACON_SLOT = "0xa3f0ad74e5423aebfd80d3ef4346578335a9a72aeaee59ff6cb3582b35133d50";
const CLONE_PREFIX = "0x363d3d373d3d3d363d73";

const word = (hex, i) => hex.slice(2 + 64 * i, 2 + 64 * (i + 1));
const wordAddr = (w) => "0x" + w.slice(24).toLowerCase();
const signed24 = (w) => { const v = parseInt(w.slice(-6), 16); return v >= 0x800000 ? v - 0x1000000 : v; };
const pad32 = (hex) => hex.replace(/^0x/, "").toLowerCase().padStart(64, "0");
const int32word = (v) => (v >= 0 ? v.toString(16).padStart(64, "0") : (BigInt(v) + (1n << 256n)).toString(16));

/** PoolId = keccak256(abi.encode(PoolKey)). Used to prove the key we read belongs to this pool. */
function poolIdOf(key) {
  const enc = pad32(key.currency0) + pad32(key.currency1) + key.fee.toString(16).padStart(64, "0") + int32word(key.tickSpacing) + pad32(key.hooks);
  return keccak256(hexBytes(enc));
}

/** Decodes a PoolManager Initialize log. Returns null unless the key re-hashes to the pool id in the log. */
function keyFromLog(log) {
  if (!log?.topics || log.topics.length < 4 || String(log.topics[0]).toLowerCase() !== INIT_TOPIC) return null;
  const data = String(log.data ?? "");
  if (data.length < 2 + 64 * 3) return null;
  const key = {
    currency0: wordAddr(log.topics[2].slice(2)), currency1: wordAddr(log.topics[3].slice(2)),
    fee: parseInt(word(data, 0).slice(-6), 16), tickSpacing: signed24(word(data, 1)), hooks: wordAddr(word(data, 2)),
  };
  if (poolIdOf(key) !== String(log.topics[1]).toLowerCase()) return null;
  return { ...key, poolManager: String(log.address ?? "").toLowerCase(), block: parseInt(log.blockNumber ?? "0x0", 16) };
}

function makeV4Hooks({ http, rpcUrl, known = {}, baselineToken = null, gapMs = 150 }) {
  const memo = {}; // used when the caller has no state object to cache into
  // the public Robinhood RPC rate-limits hard: space calls out and back off on 429 instead of reading it as "no data"
  let last = 0;
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  async function rpc(method, params) {
    for (let attempt = 0; ; attempt++) {
      const wait = last + gapMs - Date.now(); if (wait > 0) await sleep(wait);
      last = Date.now();
      const r = await http(rpcUrl, { jsonrpc: "2.0", id: 1, method, params });
      const j = r.json ?? { error: { code: r.status, message: `HTTP ${r.status}` } };
      const limited = r.status === 429 || j.error?.code === 429 || /too many requests|rate limit/i.test(j.error?.message ?? "");
      if (!limited || attempt >= 4) return j;
      await sleep(Math.min(8000, 800 * 2 ** attempt));
    }
  }

  async function blockAt(tsSec) {
    const head = parseInt((await rpc("eth_blockNumber", [])).result, 16);
    if (!Number.isFinite(head)) return null;
    let lo = 0, hi = head;
    for (let i = 0; i < 40 && lo < hi; i++) {
      const mid = Math.floor((lo + hi) / 2);
      const b = (await rpc("eth_getBlockByNumber", ["0x" + mid.toString(16), false])).result;
      if (!b) return null;
      if (parseInt(b.timestamp, 16) < tsSec) lo = mid + 1; else hi = mid;
    }
    return { block: lo, head };
  }

  /** Finds the pool key for a v4 pool id. Tries the whole chain in one query, then walks forward from the pair's birth. */
  async function poolKey(poolId, createdAtMs, state) {
    const id = poolId.toLowerCase();
    const cache = state ? (state.v4pools = state.v4pools ?? {}) : (memo.pools = memo.pools ?? {});
    if (cache[id]) return cache[id];
    const pick = (logs) => { for (const l of logs ?? []) { const k = keyFromLog(l); if (k) return k; } return null; };
    let key = null;
    const all = await rpc("eth_getLogs", [{ topics: [INIT_TOPIC, id], fromBlock: "0x0", toBlock: "latest" }]);
    memo.lastError = all.error ? String(all.error.message ?? all.error.code).slice(0, 100) : null;
    if (!all.error) key = pick(all.result);
    else if (createdAtMs) {
      const at = await blockAt(Math.floor(createdAtMs / 1000) - 3600);
      if (at) {
        let step = 50000;
        for (let start = at.block, calls = 0; start <= at.head && calls < 25 && !key; calls++) {
          const end = Math.min(at.head, start + step - 1);
          const r = await rpc("eth_getLogs", [{ topics: [INIT_TOPIC, id], fromBlock: "0x" + start.toString(16), toBlock: "0x" + end.toString(16) }]);
          if (r.error) { if (step > 1000) { step = Math.floor(step / 5); continue; } break; }
          key = pick(r.result);
          start = end + 1;
        }
      }
    }
    if (key) {
      cache[id] = key; // a pool key never changes
      const ids = Object.keys(cache);
      if (ids.length > 500) delete cache[ids[0]];
    }
    return key;
  }

  /** What the hook contract itself looks like: does it exist, can it be swapped out, does someone own it. */
  async function hookContract(hook) {
    const code = (await rpc("eth_getCode", [hook, "latest"])).result;
    if (typeof code !== "string") return { known: false };
    if (code === "0x") return { known: true, hasCode: false };
    const lc = code.toLowerCase();
    const clone = lc.startsWith(CLONE_PREFIX) ? "0x" + lc.slice(CLONE_PREFIX.length, CLONE_PREFIX.length + 40) : null;
    const impl = await rpc("eth_getStorageAt", [hook, IMPL_SLOT, "latest"]);
    const beacon = await rpc("eth_getStorageAt", [hook, BEACON_SLOT, "latest"]);
    const owner = await rpc("eth_call", [{ to: hook, data: "0x8da5cb5b" }, "latest"]);
    const slotAddr = (r) => (typeof r.result === "string" && /^0x0*[1-9a-f]/i.test(r.result) ? wordAddr(pad32(r.result)) : null);
    const ownerAddr = typeof owner.result === "string" && owner.result.length >= 66 ? wordAddr(owner.result.slice(2, 66)) : null;
    return {
      known: true, hasCode: true, clone,
      upgradeable: !!(slotAddr(impl) || slotAddr(beacon)), implementation: slotAddr(impl), beacon: slotAddr(beacon),
      owner: ownerAddr && ownerAddr !== ZERO ? ownerAddr : null,
    };
  }

  /** The launchpad's own hook: the hook on the bot's own token pool. A standard launchpad hook is not a red flag. */
  async function baselineHooks(pairsFor, state) {
    const out = new Map(Object.entries(known).map(([a, label]) => [a.toLowerCase(), label]));
    if (!baselineToken) return out;
    const store = state ?? memo;
    const b = store.v4baseline;
    if (b?.hook && Date.now() - b.t < 7 * 864e5) { out.set(b.hook, b.label); return out; }
    for (const p of (await pairsFor(baselineToken)).filter(isV4)) {
      const key = await poolKey(p.pairAddress, p.pairCreatedAt, state);
      if (key?.hooks && key.hooks !== ZERO) {
        const label = "standard musepad launch hook"; // never name the bot's own token in reports about other tokens
        store.v4baseline = { hook: key.hooks, label, t: Date.now() };
        out.set(key.hooks, label);
        break;
      }
    }
    return out;
  }

  /**
   * Full read for one v4 pool. `pair` is a DexScreener pair whose pairAddress is the 32-byte pool id.
   * Returns null when this is not a v4 pool or the key can't be read (never guess on missing data).
   */
  async function inspect(pair, standard, state) {
    if (!isV4(pair)) return null;
    const key = await poolKey(pair.pairAddress, pair.pairCreatedAt, state);
    if (!key) return { poolId: pair.pairAddress, readable: false, why: memo.lastError ?? "no Initialize event found for this pool id" };
    const perms = key.hooks === ZERO ? [] : permissionsOf(key.hooks);
    const dynamicFee = key.fee === DYNAMIC_FEE;
    const base = { poolId: pair.pairAddress.toLowerCase(), readable: true, key, hook: key.hooks, perms, dynamicFee, feePct: dynamicFee ? null : key.fee / 1e4, poolManager: key.poolManager };
    if (key.hooks === ZERO) return { ...base, none: true, risk: [], points: 0 };
    const label = standard.get(key.hooks) ?? null;
    const contract = await hookContract(key.hooks);
    const risk = [];
    let points = 0;
    const add = (text, pts) => { risk.push({ text, pts }); points += pts; };
    const swapDelta = perms.includes("beforeSwapReturnsDelta") || perms.includes("afterSwapReturnsDelta");
    if (!label) {
      if (swapDelta) add("custom v4 hook can change swap amounts", 30);
      if (dynamicFee && perms.includes("beforeSwap")) add("custom v4 hook sets the swap fee per trade", 20);
      if (contract.upgradeable && (swapDelta || dynamicFee)) add("that hook is upgradeable", 20);
      if (contract.known && contract.hasCode === false) add("hook address has no code", 10);
    }
    return { ...base, standard: label, contract, risk, points };
  }

  return { inspect, baselineHooks, poolKey, hookContract, rpc };
}

/** DexScreener lists v4 pools by their 32-byte pool id instead of a 20-byte pair address. */
const isV4 = (p) => /^0x[0-9a-fA-F]{64}$/.test(String(p?.pairAddress ?? ""));

/** One line for humans. */
function hookLine(h) {
  if (!h) return null;
  if (!h.readable) return "🪝 v4 hook: pool key not readable right now, hook not checked.";
  if (h.none) return "🪝 v4 hook: none. plain pool, no custom code runs in swaps.";
  const short = `${h.hook.slice(0, 6)}…${h.hook.slice(-4)}`;
  const powers = h.perms.filter((p) => /Swap/.test(p));
  const fee = h.dynamicFee ? "fee set by the hook per trade" : `fee ${h.feePct}%`;
  const c = h.contract ?? {};
  const upg = c.known ? (c.upgradeable ? "upgradeable" : "not upgradeable") : "upgradeability unknown";
  if (h.standard) return `🪝 v4 hook ${short}: ${h.standard}. ${fee}, ${upg}.`;
  return `🪝 v4 hook ${short}: custom. swap powers: ${powers.length ? powers.join(", ") : "none"}. ${fee}, ${upg}${c.owner ? `, owned by ${c.owner.slice(0, 6)}…${c.owner.slice(-4)}` : ""}.`;
}
return { keccak256, INIT_TOPIC, PERMISSIONS, permissionsOf, poolIdOf, keyFromLog, makeV4Hooks, isV4, hookLine };
})();

const __sim_runtime = (() => {
// GENERATED from bot/Sim.sol. Do not edit by hand.
// solc 0.8.26, evm cancun, via-ir, optimizer 200 runs, bytecode_hash none. Rebuild: see the header of bot/sim.mjs.
const SIM_RUNTIME = "0x6080604052600436101561001a575b3615610018575f80fd5b005b5f803560e01c80637f70be111461077f57806391dd7346146102485763d41b92bd14610046575061000e565b346102455761010036600319011261024557610060610821565b60a03660231901126102005761007461084b565b3033036102145760405183926024356001600160a01b038116908190036102105760208301526044356001600160a01b0381169081900361021057604083015260643562ffffff81168091036102105760608301526084358060020b80910361021057608083015260a4356001600160a01b03811692908390036102105784936101409360a0830152151560c082015260e43560e082015260e0815261011c6101008261087e565b6040519485809481936348c8949160e01b835260206004840152602483019061085a565b03926001600160a01b03165af1918215610204578092610181575b50506020815191818082019384920101031261017d5760209051604051908152f35b5f80fd5b9091503d8082843e610193818461087e565b8201916020818403126102005780519067ffffffffffffffff82116101fc570182601f82011215610200578051906101ca82610960565b936101d8604051958661087e565b828552602083830101116101fc57908060208093018386015e830101525f8061015b565b8280fd5b5080fd5b604051903d90823e3d90fd5b8480fd5b60405162461bcd60e51b815260206004820152600960248201526873656c66206f6e6c7960b81b6044820152606490fd5b80fd5b503461017d57602036600319011261017d5760043567ffffffffffffffff811161017d573660238201121561017d57806004013567ffffffffffffffff811161017d57810136602482011161017d5781900360e0811261017d5760a01361017d5760405160a0810181811067ffffffffffffffff821117610750576040526102d260248301610837565b81526102e060448301610837565b90602081019182526102f4606484016108af565b9060408101918252610308608485016108bf565b6060820190815261031b60a48601610837565b6080830190815260c4860135958615159081880361017d5760e4013591600160ff1b83146106ef578715610764576401000276a4935b604051926060840184811067ffffffffffffffff8211176107505760409081529084525f94850360208086019182526001600160a01b039788168684019081529251633cf3645360e21b81528951891660048201528b5189166024820152995162ffffff1660448b0152925160020b60648a01529251861660848901529251151560a4880152905160c4870152905190921660e485015261012061010485015261012484018190528390610144908290335af19182156106e4575f9261071c575b508160801d600f0b91600f0b935f14610703575191516001600160a01b03908116939216905b600f0b5f8112610503575b50508281600f0b135f146104fb576001600160801b0316905b81610496575b610492826040519060208201526020815261047e60408261087e565b60405191829160208352602083019061085a565b0390f35b333b156101fc57604051630b0d9c0960e01b81526001600160a01b03909116600482015230602482015260448101829052828160648183335af180156104f05715610462576104e683809261087e565b6102005781610462565b6040513d85823e3d90fd5b50819061045c565b6f7fffffffffffffffffffffffffffffff1981146106ef575f036001600160801b03166001600160a01b038216806105a05750604051630476982d60e21b8152915060209082906004908290335af1801561059557610566575b505b5f80610443565b6105879060203d60201161058e575b61057f818361087e565b8101906108a0565b505f61055d565b503d610575565b6040513d86823e3d90fd5b333b1561017d5760405190632961046560e21b825260048201525f8160248183335af180156106e4576106cd575b508491829182604051602081019263a9059cbb60e01b845233602483015260448201526044815261060060648261087e565b51925af161060c61097c565b81610691575b501561065f57604051630476982d60e21b815260208160048187335af1801561059557610640575b5061055f565b6106589060203d60201161058e5761057f818361087e565b505f61063a565b60405162461bcd60e51b815260206004820152600a6024820152691c185e4819985a5b195960b21b6044820152606490fd5b80518015925082156106a6575b50505f610612565b81925090602091810103126106c9576020015180151581036106c9575f8061069e565b8380fd5b6106db919295505f9061087e565b5f93905f6105ce565b6040513d5f823e3d90fd5b634e487b7160e01b5f52601160045260245ffd5b915191516001600160a01b039081169391921690610438565b9091506020813d602011610748575b816107386020938361087e565b8101031261017d5751905f610412565b3d915061072b565b634e487b7160e01b5f52604160045260245ffd5b73fffd8963efd1fc6a506488495d951d5263988d2593610351565b3461017d5761014036600319011261017d57610799610821565b60a036602319011261017d576107ad61084b565b906101043591821515830361017d5760a0926107d192610124359260e435916109b8565b6104926040519283926020845260ff8151166020850152602081015160408501526040810151606085015260608101516080850152608081015182850152015160c08084015260e083019061085a565b600435906001600160a01b038216820361017d57565b35906001600160a01b038216820361017d57565b60c43590811515820361017d57565b805180835260209291819084018484015e5f828201840152601f01601f1916010190565b90601f8019910116810190811067ffffffffffffffff82111761075057604052565b9081602091031261017d575190565b359062ffffff8216820361017d57565b35908160020b820361017d57565b6001600160a01b039182168152610100810195949360e09391929091906108f382610837565b16602084015260018060a01b0361090c60208301610837565b16604084015262ffffff610922604083016108af565b166060840152610934606082016108bf565b60020b608084015261094f608060018060a01b039201610837565b1660a0830152151560c08201520152565b67ffffffffffffffff811161075057601f01601f191660200190565b3d156109a6573d9061098d82610960565b9161099b604051938461087e565b82523d5f602084013e565b606090565b919082039182116106ef57565b9493919460405160c0810181811067ffffffffffffffff821117610750576040525f815260208101965f88525f60408301525f60608301525f608083015260a0820190606082528298855f14610bcf576024356001600160a01b038116810361017d57905b8615610bb6576044356001600160a01b038116810361017d57975b9815610af3575b5050505050602460209160018852610a75610a5986610be8565b96604051958694859463d41b92bd60e01b8652600486016108cd565b03815f305af15f9181610abf575b50610a9c5750505090610a9461097c565b60a082015290565b610ab49291610aaf916060870152610be8565b6109ab565b608083015260028252565b9091506020813d602011610aeb575b81610adb6020938361087e565b8101031261017d5751905f610a83565b3d9150610ace565b81929398506020610b0d610b2d939c999798969b9c610be8565b946040518094819263d41b92bd60e01b8352891560248d600486016108cd565b03815f305af15f9281610b82575b50610b55575050505050505050610b5061097c565b905290565b602095979a995060249496985091610aaf91610b72949352610be8565b80604089015294915f8080610a3f565b9092506020813d602011610bae575b81610b9e6020938361087e565b8101031261017d5751915f610b3b565b3d9150610b91565b6024356001600160a01b038116810361017d5797610a38565b6044356001600160a01b038116810361017d5790610a1d565b6001600160a01b031680610bfb57504790565b6020602491604051928380926370a0823160e01b82523060048301525afa9081156106e4575f91610c2a575090565b90506020813d602011610c51575b81610c456020938361087e565b8101031261017d575190565b3d9150610c3856fea164736f6c634300081a000a";
return { SIM_RUNTIME };
})();

const __sim = (() => {
// Real buy-and-sell simulation on the token's own Uniswap v4 pool. Nothing is sent and nothing is paid:
// a small contract (bot/Sim.sol) is placed at a scratch address with an eth_call state override, given some of
// the quote currency, and asked to buy the token and sell it straight back through the real PoolManager, hook and
// token code, pinned to one block. What comes back is measured, not estimated.
//
// Known ways a simulation lies, and what this does about each:
// - the simulator itself breaks (RPC quirk, unsupported override): a failed sell is re-run on a known-good control
//   token in the same block; if the control fails too, the result is thrown away, not reported.
// - anti-bot cooldowns block a sell in the same block as the buy: a failed sell is re-run as a plain holder
//   (balance set directly, no buy first). If the holder can sell, it's a cooldown, not a honeypot.
// - a fresh pool with thin liquidity: not simulated below a liquidity floor.
// - a result is only true for that block: the block number travels with every result.
// - a token that recognises the simulator (a fixed scratch address, a known tx.origin, the gas price of 0 an eth_call
//   uses by default) could let the simulation sell and block real buyers: the simulator and sender addresses are new
//   for every block, derived from a secret per-process seed, and every call carries the chain's real gas price.
//
// Zero dependencies. Rebuild the runtime after editing bot/Sim.sol with solc 0.8.26 (evm cancun, via-ir,
// optimizer 200 runs, no metadata hash) and paste the deployed bytecode into bot/sim-runtime.mjs.
const { keccak256 } = __v4hooks;
const { SIM_RUNTIME } = __sim_runtime;

const ZERO = "0x0000000000000000000000000000000000000000";
const DYNAMIC_FEE = 0x800000;
const SEL_ROUND_TRIP = "0x7f70be11";
const SEL_BALANCE_OF = "0x70a08231";
const SEL_DECIMALS = "0x313ce567";

const hex32 = (v) => BigInt.asUintN(256, BigInt(v)).toString(16).padStart(64, "0");
const addr32 = (a) => a.replace(/^0x/, "").toLowerCase().padStart(64, "0");
const hexBytes = (h) => Uint8Array.from((h.replace(/^0x/, "").match(/../g) ?? []).map((b) => parseInt(b, 16)));
const toHexQty = (v) => "0x" + BigInt(v).toString(16);

function encodeRoundTrip(pm, key, tokenIs0, quoteIn, sellOnly, sellAmount) {
  return SEL_ROUND_TRIP + addr32(pm) + addr32(key.currency0) + addr32(key.currency1) + hex32(key.fee) + hex32(key.tickSpacing) +
    addr32(key.hooks) + hex32(tokenIs0 ? 1 : 0) + hex32(quoteIn) + hex32(sellOnly ? 1 : 0) + hex32(sellAmount);
}

/** Decodes Sim.Result: (uint8 stage, uint256 tokenOwed, uint256 tokenGot, uint256 quoteOwed, uint256 quoteBack, bytes revertData). */
function decodeResult(ret) {
  const h = ret.replace(/^0x/, "");
  const w = (i) => BigInt("0x" + h.slice(64 * i, 64 * (i + 1)));
  const base = Number(w(0)) / 32; // offset of the tuple
  const at = (i) => w(base + i);
  const bytesOff = base + Number(at(5)) / 32;
  const len = Number(w(bytesOff));
  const revertData = "0x" + h.slice(64 * (bytesOff + 1), 64 * (bytesOff + 1) + len * 2);
  return { stage: Number(at(0)), tokenOwed: at(1), tokenGot: at(2), quoteOwed: at(3), quoteBack: at(4), revertData };
}

/** Short human reason from revert bytes: Error(string), a v4 wrapped error, or the raw selector. */
function revertReason(data) {
  const h = String(data ?? "").replace(/^0x/, "");
  if (!h) return "reverted without a reason";
  if (h.startsWith("08c379a0") && h.length >= 8 + 128) {
    const len = parseInt(h.slice(8 + 64, 8 + 128), 16);
    const txt = new TextDecoder().decode(hexBytes(h.slice(8 + 128, 8 + 128 + len * 2)));
    return txt.slice(0, 80) || "reverted";
  }
  return KNOWN_ERRORS[h.slice(0, 8)] ?? `error 0x${h.slice(0, 8)}`;
}
const KNOWN_ERRORS = {
  "5212cba1": "the token delivered less than it owed the pool (transfer tax or blocked transfer)",
  "90bfb865": "the pool's hook reverted",
  "7c9c6e8f": "price limit already exceeded",
  "486aa307": "pool not initialized",
};

/** Candidate storage slots for balanceOf[holder] across common ERC20 layouts, used when eth_createAccessList is missing. */
function candidateSlots(holder) {
  const out = [];
  for (let s = 0; s < 10; s++) {
    out.push(keccak256(hexBytes(addr32(holder) + hex32(s)))); // solidity mapping
    out.push(keccak256(hexBytes(hex32(s) + addr32(holder)))); // vyper mapping
  }
  out.push(keccak256(hexBytes(addr32(holder) + "52c63247e1f47db19d5ce0460030c497f067ca4cebf71ba98eeadabe20bace00"))); // OZ v5 upgradeable
  out.push(keccak256(hexBytes(holder.replace(/^0x/, "").toLowerCase() + "0000000000000000" + "87a211a2"))); // solady
  return out;
}

/**
 * rpc(method, params) → JSON-RPC response object ({result} or {error}).
 * control: optional async () => ({ key, token, quoteIn }) for a known-good pool, used to validate a failed sell.
 * seed: secret the per-block simulator and sender addresses derive from (random per process; fixed only for recorded
 * test fixtures, so a replay asks the same questions).
 */
function makeSim({ rpc, control = null, seed = null }) {
  const slotCache = new Map();
  const decCache = new Map();
  const secret = seed ?? Array.from(globalThis.crypto.getRandomValues(new Uint8Array(16)), (b) => b.toString(16).padStart(2, "0")).join("");
  const derive = (tag, block) => "0x" + keccak256(new TextEncoder().encode(`${secret}:${tag}:${block}`)).slice(-40);
  /** Simulator and sender addresses for one block: unpredictable, and different every block. */
  const actors = (block) => ({ sim: derive("sim", block), from: derive("from", block) });
  const gasCache = new Map();
  /** The chain's gas price for this block (never 0: a token can tell an eth_call from a real transaction by that). */
  async function gasPrice(block) {
    if (!gasCache.has(block)) {
      const r = await rpc("eth_gasPrice", []).catch(() => null);
      const g = typeof r?.result === "string" && BigInt(r.result) > 0n ? r.result : "0x3b9aca00"; // 1 gwei if unreadable
      gasCache.clear(); gasCache.set(block, g);
    }
    return gasCache.get(block);
  }

  async function call(to, data, block, overrides) {
    const { from } = actors(block);
    // the sender pays real gas, so it is given the ETH to cover it (and nothing else changes about it)
    const over = { ...overrides, [from]: { ...(overrides?.[from] ?? {}), balance: "0xc9f2c9cd04674edea40000000" } };
    return rpc("eth_call", [{ from, to, data, gas: "0x1c9c380", gasPrice: await gasPrice(block) }, block, over]);
  }

  async function decimals(token, block) {
    if (token === ZERO) return 18;
    if (decCache.has(token)) return decCache.get(token);
    const r = await call(token, SEL_DECIMALS, block, {});
    const d = typeof r.result === "string" && r.result.length > 2 ? Number(BigInt(r.result)) : null;
    if (d !== null && d <= 36) decCache.set(token, d);
    return d;
  }

  /** Finds the storage slot holding balanceOf[holder] by writing a marker and reading it back. */
  async function balanceSlot(token, holder, block) {
    const k = `${token}:${holder}`;
    if (slotCache.has(k)) return slotCache.get(k);
    const data = SEL_BALANCE_OF + addr32(holder);
    let keys = [];
    const al = await rpc("eth_createAccessList", [{ from: actors(block).from, to: token, data }, block]);
    for (const e of al.result?.accessList ?? []) if (String(e.address).toLowerCase() === token) keys.push(...(e.storageKeys ?? []));
    keys = [...new Set([...keys, ...candidateSlots(holder)])];
    const marker = 0x5117_5117_5117n;
    for (const slot of keys) {
      const r = await call(token, data, block, { [token]: { stateDiff: { [slot]: "0x" + hex32(marker) } } });
      if (typeof r.result === "string" && r.result.length > 2 && BigInt(r.result) === marker) { slotCache.set(k, slot); return slot; }
    }
    slotCache.set(k, null);
    return null;
  }

  /** Builds the override: Sim code at this block's simulator address, plus `amount` of `currency` in its balance. Null if it can't be funded. */
  async function funded(currency, amount, block) {
    const { sim } = actors(block);
    const o = { [sim]: { code: SIM_RUNTIME } };
    if (currency === ZERO) { o[sim].balance = toHexQty(amount); return o; }
    const slot = await balanceSlot(currency, sim, block);
    if (!slot) return null;
    o[currency] = { stateDiff: { [slot]: "0x" + hex32(amount) } };
    return o;
  }

  /** One round trip on one pool. sellOnly: fund the Sim with `amount` of the token and only sell. */
  async function roundTrip({ key, token, amount, sellOnly = false, block }) {
    const tokenIs0 = key.currency0 === token;
    const quote = tokenIs0 ? key.currency1 : key.currency0;
    const over = await funded(sellOnly ? token : quote, amount, block);
    if (!over) return { stage: -1, why: `couldn't find the balance slot of ${sellOnly ? "the token" : "the quote currency"}` };
    const r = await call(actors(block).sim, encodeRoundTrip(key.poolManager, key, tokenIs0, sellOnly ? 0n : amount, sellOnly, sellOnly ? amount : 0n), block, over);
    if (r.error) return { stage: -1, why: `eth_call failed: ${String(r.error.message ?? r.error.code).slice(0, 100)}` };
    try { return decodeResult(r.result); } catch { return { stage: -1, why: "unreadable simulator output" }; }
  }

  /**
   * Full read. key: v4 pool key incl. poolManager. token: lowercased token address.
   * quoteIn: amount of the quote currency to buy with (base units). Returns the raw legs; classify() judges them.
   */
  async function run({ key, token, quoteIn }) {
    const head = (await rpc("eth_blockNumber", [])).result;
    if (typeof head !== "string") return { ok: false, why: "no block number from the RPC" };
    const block = head;
    const main = await roundTrip({ key, token, amount: quoteIn, block });
    const out = { ok: true, block: parseInt(block, 16), quoteIn, main };
    if (main.stage !== 1) return out;
    // sell failed: is it the simulator, a cooldown, or the token?
    if (control) {
      try {
        const c = await control();
        if (c) out.control = await roundTrip({ key: c.key, token: c.token, amount: c.quoteIn, block });
      } catch (e) { out.control = { stage: -1, why: String(e).slice(0, 100) }; }
    }
    if (main.tokenOwed > 0n) out.holder = await roundTrip({ key, token, amount: main.tokenOwed, sellOnly: true, block });
    return out;
  }

  /**
   * Exact-size quote on the live pool, plus a small reference trade in the same block for the mid price.
   * side "buy": spend `amount` of the quote currency. side "sell": sell `amount` of the token (as a plain holder).
   */
  async function plan({ key, token, side, amount, refAmount }) {
    const head = (await rpc("eth_blockNumber", [])).result;
    if (typeof head !== "string") return { ok: false, why: "no block number from the RPC" };
    const sell = side === "sell";
    const big = await roundTrip({ key, token, amount, sellOnly: sell, block: head });
    const small = await roundTrip({ key, token, amount: refAmount, sellOnly: sell, block: head });
    const got = (r) => (sell ? (r.stage === 2 ? r.quoteBack : null) : r.stage >= 1 ? r.tokenGot : null);
    return {
      ok: true, block: parseInt(head, 16), side: sell ? "sell" : "buy", amountIn: amount, out: got(big), refIn: refAmount, refOut: got(small),
      stage: big.stage, why: big.why ?? null, revertData: big.revertData ?? null,
      // a buy whose immediate sell-back reverts is a trap even if the buy itself works
      sellBackFails: !sell && big.stage === 1, roundTripBack: !sell && big.stage === 2 ? big.quoteBack : null,
    };
  }

  /**
   * Measured exit size: the biggest single sell (token base units) whose price impact stays under `target`, found by
   * selling as a plain holder on the live pool at one block. Counts only what the pool really pays: for a Doppler v4
   * multicurve that is the in-range liquidity, not the out-of-range, single-sided part a full-position figure includes.
   */
  async function exitSize({ key, token, refIn, guessIn, target = 0.02 }) {
    const head = (await rpc("eth_blockNumber", [])).result;
    if (typeof head !== "string") return null;
    const sellOut = async (amount) => { const r = await roundTrip({ key, token, amount, sellOnly: true, block: head }); return r.stage === 2 ? r.quoteBack : null; };
    const r = await searchExit({ sellOut, refIn, guessIn, target });
    return r ? { ...r, block: parseInt(head, 16) } : null;
  }

  return { run, plan, roundTrip, exitSize, balanceSlot, decimals, block: async () => (await rpc("eth_blockNumber", [])).result };
}

/**
 * Searches for the largest sell whose price impact (average price vs a small reference sell in the same block, so pool
 * and hook fees cancel out) stays under `target`. sellOut(amount) → quote received, or null when the sell reverts.
 * Pure apart from sellOut, so it is unit tested. Returns { amountIn, impact, atLeast, calls } or null (no reference).
 * atLeast: even the largest size tried stayed under target, so the real exit size is bigger than amountIn.
 */
async function searchExit({ sellOut, refIn, guessIn, target = 0.02, steps = 8, maxGrow = 4 }) {
  let calls = 0;
  const out = async (x) => { calls++; return sellOut(x); };
  const refOut = await out(refIn);
  if (!refOut || refOut <= 0n || refIn <= 0n) return null;
  const rateRef = Number((refOut * 10n ** 18n) / refIn) / 1e18;
  const impactAt = async (x) => { const o = await out(x); return o === null ? 1 : Math.max(0, 1 - Number((o * 10n ** 18n) / x) / 1e18 / rateRef); };
  let lo = refIn, loImpact = 0, hi = guessIn > refIn ? guessIn : refIn * 10n;
  let hiImpact = await impactAt(hi);
  for (let g = 0; hiImpact < target && g < maxGrow; g++) { lo = hi; loImpact = hiImpact; hi *= 4n; hiImpact = await impactAt(hi); }
  if (hiImpact < target) return { amountIn: hi, impact: hiImpact, atLeast: true, calls };
  for (let i = 0; i < steps; i++) {
    const mid = BigInt(Math.floor(Math.sqrt(Number(lo) * Number(hi))));
    if (mid <= lo || mid >= hi) break;
    const m = await impactAt(mid);
    if (m < target) { lo = mid; loImpact = m; } else hi = mid;
  }
  return { amountIn: lo, impact: loImpact, atLeast: false, calls };
}

/**
 * Turns an exact-size simulation into a trade plan. Pure, unit tested (and mirrored in x402/_shared/v4.ts).
 * volatilityPct: recent move in % (DexScreener m5 / h1), used to size slippage for the time between quote and inclusion.
 * Returns { verdict: GO | CAUTION | NO_GO, impactPct, slippagePct, minOutFraction, split, reasons[] }.
 */
function planAdvice(res, { m5 = 0, h1 = 0, usd = null } = {}) {
  if (!res?.ok) return { verdict: "UNAVAILABLE", reasons: [res?.why ?? "no simulation"] };
  if (res.out === null || res.out === 0n) {
    const what = res.side === "sell" ? "the sell" : "the buy";
    return { verdict: "NO_GO", reasons: [`${what} reverted in simulation (${res.why ?? revertReason(res.revertData)})`] };
  }
  const reasons = [];
  let impact = 0;
  if (res.refOut && res.refOut > 0n && res.refIn > 0n) {
    // price per unit at size vs at the reference size, same block
    const atSize = Number((res.out * 10n ** 18n) / res.amountIn) / 1e18;
    const atRef = Number((res.refOut * 10n ** 18n) / res.refIn) / 1e18;
    impact = Math.max(0, 1 - atSize / atRef);
  }
  const impactPct = pct(impact);
  const vol = Math.max(Math.abs(m5 ?? 0), Math.abs(h1 ?? 0) / 3);
  const slippagePct = Math.round(Math.min(5, Math.max(0.5, 0.5 + 1.5 * vol)) * 10) / 10;
  const minOutFraction = 1 - slippagePct / 100;
  let verdict = "GO";
  if (res.sellBackFails) { verdict = "NO_GO"; reasons.push("the buy works but selling it straight back reverts: you could get in and not out"); }
  if (impactPct > 8) { verdict = "NO_GO"; reasons.push(`price impact ${impactPct}% at this size`); }
  else if (impactPct > 2) { if (verdict === "GO") verdict = "CAUTION"; reasons.push(`price impact ${impactPct}% at this size`); }
  if (res.roundTripBack !== null && res.amountIn > 0n) {
    const rt = pct(Math.max(0, 1 - Number((res.roundTripBack * 1_000_000n) / res.amountIn) / 1e6));
    if (rt >= 20 && verdict !== "NO_GO") { verdict = rt >= 50 ? "NO_GO" : "CAUTION"; reasons.push(`buying and selling back at this size loses ${rt}%`); }
  }
  // split so each piece stays near 1% impact (impact grows roughly linearly with size at these depths)
  const pieces = impactPct > 2 ? Math.min(10, Math.ceil(impactPct / 1)) : 1;
  const split = pieces > 1 ? { pieces, usdEach: usd ? Math.round((usd / pieces) * 100) / 100 : null, note: "a few blocks apart, re-quote each" } : null;
  if (!reasons.length) reasons.push("clean at this size");
  return { verdict, impactPct, slippagePct, minOutFraction, split, reasons };
}

const pct = (x) => Math.round(x * 1000) / 10;
const ratio = (a, b) => (b > 0n ? Number((a * 1_000_000n) / b) / 1_000_000 : null);

/**
 * Turns raw legs into flags. Pure, so it is unit tested.
 * Returns { status, line, flags: [{ text, pts, critical }], roundTripLossPct, buyTaxPct }.
 */
function classify(res, { fee = null, sizeUsd = null, hasHook = false } = {}) {
  const size = sizeUsd ? `$${sizeUsd < 10 ? sizeUsd.toFixed(2) : Math.round(sizeUsd)}` : "a small";
  if (!res?.ok) return { status: "unavailable", line: `🧪 trade simulation unavailable (${res?.why ?? "no result"}).`, flags: [] };
  const m = res.main;
  if (m.stage === -1) return { status: "unavailable", line: `🧪 trade simulation unavailable (${m.why}).`, flags: [] };
  if (m.stage === 0) return { status: "buy-failed", line: `🧪 a simulated ${size} buy reverted (${revertReason(m.revertData)}), so buying and selling couldn't be tested. not scored.`, flags: [] };
  const buyTax = m.tokenOwed > 0n ? 1 - ratio(m.tokenGot, m.tokenOwed) : 0;
  const flags = [];
  const buyTaxPct = pct(Math.max(0, buyTax));
  if (buyTaxPct > 10) flags.push({ text: `buy tax ${Math.round(buyTaxPct)}% (simulated)`, pts: 15 });
  if (m.stage === 1) {
    const reason = revertReason(m.revertData);
    const c = res.control;
    if (c && c.stage !== 2) return { status: "inconclusive", line: `🧪 simulated sell failed, but so did a known-good control token in the same block, so the simulator is at fault. not scored.`, flags: [], buyTaxPct };
    const h = res.holder;
    if (h?.stage === 2) {
      flags.push({ text: "can't sell in the same block as buying (anti-bot cooldown)", pts: 15 });
      return { status: "cooldown", line: `🧪 simulated ${size} buy worked; selling in the same block reverted (${reason}), but a plain holder could sell. looks like an anti-bot cooldown, not a honeypot. block ${res.block}.`, flags, buyTaxPct };
    }
    if (h && h.stage >= 0 && h.stage < 2 && c?.stage === 2) {
      flags.push({ text: "sell reverted in simulation (honeypot)", pts: 100, critical: true });
      return { status: "honeypot", line: `🧪 simulated ${size} buy worked, but selling reverted (${reason}), for a fresh buyer and for a plain holder, while a control token sold fine in the same block. block ${res.block}.`, flags, buyTaxPct };
    }
    flags.push({ text: "sell failed in simulation (unconfirmed)", pts: 25 });
    return { status: "sell-failed", line: `🧪 simulated ${size} buy worked, but selling it back reverted (${reason}). couldn't run every cross-check, so this is scored as a warning, not a verdict. block ${res.block}.`, flags, buyTaxPct };
  }
  const back = ratio(m.quoteBack, res.quoteIn);
  const loss = Math.max(0, 1 - back);
  const lossPct = pct(loss);
  const expected = fee !== null && fee !== DYNAMIC_FEE ? pct((2 * fee) / 1e6) : null;
  if (lossPct >= 50) flags.push({ text: `simulated round trip loses ${Math.round(lossPct)}%`, pts: 100, critical: true });
  else if (lossPct >= 20) flags.push({ text: `simulated round trip loses ${Math.round(lossPct)}%`, pts: 40 });
  else if (lossPct >= 10) flags.push({ text: `simulated round trip loses ${Math.round(lossPct)}%`, pts: 20 });
  const feeNote = expected === null ? " incl. pool and hook fees"
    : hasHook && lossPct > expected + 0.5 ? ` (pool fee ~${expected}%, the rest goes to the pool's hook)`
    : ` (pool fees alone would be ~${expected}%)`;
  const taxNote = buyTaxPct > 1 ? `, ${buyTaxPct}% of the bought tokens never arrived (transfer tax)` : "";
  return { status: "ok", line: `🧪 simulated ${size} buy then sell on the real pool: ${lossPct}% round-trip cost${feeNote}${taxNote}. block ${res.block}.`, flags, roundTripLossPct: lossPct, buyTaxPct };
}
return { encodeRoundTrip, decodeResult, revertReason, makeSim, searchExit, planAdvice, classify };
})();
// ── END bundle ──

const V4H = __v4hooks.makeV4Hooks({ http, rpcUrl: RPC_URL, gapMs: 0 });
const SIM = __sim.makeSim({ rpc: V4H.rpc });
const n = (v: unknown) => (v === null || v === undefined || v === "" || !Number.isFinite(Number(v)) ? null : Number(v));
async function decimalsOf(c: string) {
  if (/^0x0{40}$/.test(c)) return 18;
  const r = await V4H.rpc("eth_call", [{ to: c, data: "0x313ce567" }, "latest"]);
  try { const d = Number(BigInt(r.result)); return d <= 36 ? d : null; } catch { return null; }
}
const units = (usd: number, pricePerUnit: number, dec: number) => (BigInt(Math.max(1, Math.floor((usd / pricePerUnit) * 1e6))) * 10n ** BigInt(dec)) / 1000000n;
const human = (v: bigint, dec: number) => Number(v) / 10 ** dec;

export default async function handler(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const address = (url.searchParams.get("address") ?? "").trim().toLowerCase();
  const usd = Number(url.searchParams.get("usd"));
  const side = (url.searchParams.get("side") ?? "buy").toLowerCase();
  const chain = (url.searchParams.get("chain") ?? "robinhood").toLowerCase();
  if (!/^0x[0-9a-f]{40}$/.test(address)) return bad(400, "invalid_address", "Pass ?address= as a 0x token address.");
  if (!(usd > 0 && usd <= 1e7)) return bad(400, "invalid_usd", "Pass ?usd= as the trade size in USD.");
  if (side !== "buy" && side !== "sell") return bad(400, "invalid_side", "side is buy or sell.");
  if (chain !== "robinhood") return bad(400, "unsupported_chain", "Exact simulation covers Robinhood Chain v4 pools. For other chains use exit-check.");
  const pairs = (await http(`https://api.dexscreener.com/tokens/v1/robinhood/${address}`)).json;
  if (!Array.isArray(pairs)) return bad(502, "upstream_unavailable", "Market data unreachable. You were not charged.");
  const p = pairs.filter((x) => __v4hooks.isV4(x) && String(x?.baseToken?.address ?? "").toLowerCase() === address)
    .sort((a, b) => (n(b.liquidity?.usd) ?? 0) - (n(a.liquidity?.usd) ?? 0))[0];
  if (!p) return bad(404, "no_v4_pool", "No Uniswap v4 pool for this token on Robinhood Chain. You were not charged.");
  const key = await V4H.poolKey(p.pairAddress, p.pairCreatedAt, null);
  if (!key) return bad(502, "pool_unreadable", "Couldn't read the pool key. You were not charged.");
  const quote = key.currency0 === address ? key.currency1 : key.currency0;
  const [tokenDec, quoteDec] = [await decimalsOf(address), await decimalsOf(quote)];
  const pUsd = n(p.priceUsd), pNat = n(p.priceNative);
  if (tokenDec === null || quoteDec === null || !pUsd || !pNat) return bad(502, "no_price", "No usable price for this pool. You were not charged.");
  const quoteUsd = pUsd / pNat;
  const [amount, ref] = side === "buy" ? [units(usd, quoteUsd, quoteDec), units(Math.min(1, usd), quoteUsd, quoteDec)] : [units(usd, pUsd, tokenDec), units(Math.min(1, usd), pUsd, tokenDec)];
  const run = SIM.plan({ key, token: address, side, amount, refAmount: ref });
  const res: any = await Promise.race([run, new Promise((r) => setTimeout(() => r(null), 20000))]);
  if (!res) return bad(504, "simulation_timeout", "The chain was too slow to simulate. You were not charged.");
  const a = __sim.planAdvice(res, { m5: n(p.priceChange?.m5) ?? 0, h1: n(p.priceChange?.h1) ?? 0, usd });
  const outDec = side === "buy" ? tokenDec : quoteDec;
  const outSym = side === "buy" ? p.baseToken?.symbol ?? null : p.quoteToken?.symbol ?? null;
  const minOut = res.out ? (res.out * BigInt(Math.round((a.minOutFraction ?? 0) * 1e6))) / 1000000n : null;
  return Response.json({
    address, chain, side, usd,
    verdict: a.verdict, reasons: a.reasons,
    impactPct: a.impactPct ?? null, slippagePct: a.slippagePct ?? null,
    expectedOut: res.out ? { raw: res.out.toString(), amount: human(res.out, outDec), symbol: outSym, token: side === "buy" ? address : quote, decimals: outDec } : null,
    amountOutMinimum: minOut !== null ? { raw: minOut.toString(), amount: human(minOut, outDec) } : null,
    split: a.split ?? null,
    pool: { poolId: p.pairAddress, poolManager: key.poolManager, hooks: key.hooks, fee: key.fee, tickSpacing: key.tickSpacing, currency0: key.currency0, currency1: key.currency1, liquidityUsd: n(p.liquidity?.usd) },
    block: res.block ?? null, checkedAt: new Date().toISOString(), disclaimer: DISCLAIMER,
  });
}
