// @ts-nocheck  (the bundle below is the bot's plain-JS module, verbatim; tests cover it)
// pretrade / approvals — self-contained x402 Cloud handler (Request → Response)
// Every token approval a wallet still has live (current allowance, not just past events), riskiest first, with
// spender code and reputation checks and a ready revoke transaction for each risky one.
const RPCS: Record<string, string> = {
  robinhood: "https://rpc.mainnet.chain.robinhood.com",
  base: "https://mainnet.base.org",
  ethereum: "https://ethereum-rpc.publicnode.com",
};
const GOPLUS_ID: Record<string, string> = { robinhood: "4663", base: "8453", ethereum: "1" };
const KNOWN = { "0x000000000022d473030f116ddee9f6b43ac78ba3": "Permit2" };
const DISCLAIMER = "Read-only scan of public chain data. Revoking costs gas and is always safe. Not financial advice.";
const bad = (status: number, error: string, hint?: string) => Response.json({ error, hint }, { status }); // >= 400: not charged
async function http(url: string, body?: unknown) {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), 10000);
  try {
    const r = await fetch(url, body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body), signal: ctrl.signal } : { headers: { accept: "application/json" }, signal: ctrl.signal });
    const text = await r.text();
    let json = null; try { json = JSON.parse(text); } catch {}
    return { ok: r.ok, status: r.status, json, text };
  } catch (e) { return { ok: false, status: 0, json: null, text: String(e) }; } finally { clearTimeout(t); }
}

// ── BEGIN bundle ── (generated by scripts/bundle-x402.mjs from bot/approvals.mjs; do not edit)
const __approvals = (() => {
// Wallet approval audit: every token approval a wallet has granted that is STILL live, who holds it, and a ready
// revoke transaction for the risky ones. Agents approve routers all day; a forgotten unlimited approval to the wrong
// contract is how a wallet gets drained weeks later.
// Reads Approval / ApprovalForAll logs where the wallet is the owner, then the CURRENT allowance for each
// (token, spender): approvals that were revoked or used up don't count. Read-only; zero dependencies.
// Public RPCs refuse whole-history log searches, so the history comes from the chain's Blockscout explorer
// (Etherscan-style getLogs over all blocks), with the RPC as a fallback.

const T_APPROVAL = "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925";
const T_APPROVAL_ALL = "0x17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31";
const UNLIMITED = 2n ** 255n;
const pad = (a) => "0x" + a.replace(/^0x/, "").toLowerCase().padStart(64, "0");
const topicAddr = (t) => "0x" + String(t).slice(-40).toLowerCase();

/** Latest approval event per (token, spender) from raw logs. Pure, unit tested. */
function latestGrants(logs) {
  const m = new Map();
  for (const l of logs ?? []) {
    const t = (l.topics ?? []).map((x) => String(x).toLowerCase());
    if (t.length < 3) continue;
    const token = String(l.address ?? "").toLowerCase(), spender = topicAddr(t[2]);
    let kind;
    if (t[0] === T_APPROVAL && t.length === 3) kind = "erc20";
    else if (t[0] === T_APPROVAL_ALL) kind = "all";
    else continue; // ERC-721 single-token approvals clear on transfer; not tracked
    const k = `${kind}|${token}|${spender}`;
    const at = [parseInt(l.blockNumber ?? "0x0", 16), parseInt(l.logIndex ?? "0x0", 16)];
    const prev = m.get(k);
    const granted = kind === "erc20" ? (() => { try { return BigInt(l.data && l.data !== "0x" ? l.data : "0x0"); } catch { return 0n; } })() : null;
    if (!prev || at[0] > prev.at[0] || (at[0] === prev.at[0] && at[1] > prev.at[1])) m.set(k, { kind, token, spender, at, block: at[0], granted });
  }
  return [...m.values()];
}

/**
 * Risk for one live grant. Pure, unit tested.
 * g: { kind, amount (bigint, erc20), spenderIsContract, spenderLabel, flagged: [] }
 */
function grantRisk(g) {
  const why = [];
  let level = "low";
  const bump = (l) => { const o = { low: 0, medium: 1, high: 2, critical: 3 }; if (o[l] > o[level]) level = l; };
  if (g.flagged?.length) {
    // reputation feeds also list well-known infrastructure that drainers route through (GoPlus flags the verified
    // 0x AllowanceHolder, for one); for a recognised spender the flag is shown, not escalated
    if (g.spenderLabel) { bump("medium"); why.push(`a reputation feed lists it for ${g.flagged.join(", ")}, but it is the known ${g.spenderLabel}`); }
    else { bump("critical"); why.push(`spender is flagged for ${g.flagged.join(", ")}`); }
  }
  if (g.spenderIsContract === false) { bump(g.kind === "all" || g.amount >= UNLIMITED ? "critical" : "high"); why.push("spender is a plain wallet, not a protocol contract"); }
  if (g.kind === "all") { bump(g.spenderLabel ? "medium" : "high"); why.push("can move every item in the collection"); }
  else if (g.amount >= UNLIMITED) { bump(g.spenderLabel ? "low" : "medium"); why.push("unlimited amount"); }
  if (!g.spenderLabel && g.spenderIsContract) why.push("unrecognised contract");
  if (g.spenderLabel) why.push(`spender: ${g.spenderLabel}`);
  return { level, why };
}

/** A zero-cost revoke for one grant, ready to sign: approve(spender, 0) or setApprovalForAll(operator, false). */
function revokeTx(g, owner) {
  const spender = g.spender.replace(/^0x/, "").padStart(64, "0");
  return g.kind === "all"
    ? { from: owner, to: g.token, data: "0xa22cb465" + spender + "0".repeat(64), value: "0x0" }
    : { from: owner, to: g.token, data: "0x095ea7b3" + spender + "0".repeat(64), value: "0x0" };
}

/** Widely used spenders, so a normal router approval isn't reported as an unknown contract. Same address on every chain. */
const KNOWN_SPENDERS = {
  "0x000000000022d473030f116ddee9f6b43ac78ba3": "Permit2 (Uniswap)",
  "0x0000000000001ff3684f28c67538d4d072c22734": "0x AllowanceHolder",
  "0x111111125421ca6dc452d289314280a0f8842a65": "1inch Router v6",
};

/** Runs fn over items with at most n in flight (public RPCs throttle bursts; one-at-a-time is too slow). */
async function inPool(items, n, fn) {
  const out = new Array(items.length);
  let next = 0;
  await Promise.all(Array.from({ length: Math.min(n, items.length) }, async () => {
    while (next < items.length) { const i = next++; out[i] = await fn(items[i], i); }
  }));
  return out;
}

const EXPLORERS = {
  robinhood: "https://robinhoodchain.blockscout.com",
  base: "https://base.blockscout.com",
  ethereum: "https://eth.blockscout.com",
};

function makeApprovals({ rpcFor, known = {}, reputation = null, http = null, explorers = EXPLORERS }) {
  known = { ...KNOWN_SPENDERS, ...known };
  // public RPCs rate-limit a burst of reads; a failed read must never look like "no approval"
  const patient = (rpc) => async (method, params) => {
    for (let i = 0; ; i++) {
      const r = await rpc(method, params);
      const limited = r?.error && (r.error.code === 429 || r.error.code === -32005 || /rate|limit|too many/i.test(r.error.message ?? ""));
      if (!limited || i >= 3) return r;
      await new Promise((ok) => setTimeout(ok, 700 * 2 ** i));
    }
  };
  /** Whole-history logs from Blockscout. null when unavailable, so the caller can fall back. */
  async function explorerLogs(chain, wallet) {
    const base = explorers[chain];
    if (!base || !http) return null;
    const all = [];
    for (const topic of [T_APPROVAL, T_APPROVAL_ALL]) {
      const r = await http(`${base}/api?module=logs&action=getLogs&fromBlock=0&toBlock=latest&topic0=${topic}&topic1=${pad(wallet)}&topic0_1_opr=and`);
      const j = r.json;
      // Blockscout answers {message:"OK", result:[…]} (some versions add status "1"); anything else (a bot wall, an error) → fall back
      const ok = j && Array.isArray(j.result) && (j.status === "1" || /^ok$/i.test(j.message ?? ""));
      const empty = j && /no (records|logs) found/i.test(j.message ?? "");
      if (!ok && !empty) return null;
      for (const l of Array.isArray(j.result) ? j.result : []) all.push({ ...l, topics: (l.topics ?? []).filter(Boolean) });
    }
    return { logs: all, source: "blockscout" };
  }
  /** RPC fallback: the whole range if the node allows it, else ever smaller windows, within a call budget. */
  async function logs(rpc, wallet, maxCalls = 60) {
    const head = parseInt((await rpc("eth_blockNumber", []))?.result ?? "0x0", 16);
    if (!head) return { error: "no block number" };
    const out = [];
    let calls = 0, lastErr = null;
    for (const topic of [T_APPROVAL, T_APPROVAL_ALL]) {
      let from = 0, step = head + 1;
      while (from <= head) {
        if (++calls > maxCalls) return { error: `history too long to scan here (${lastErr ?? "range limits"})` };
        const to = Math.min(head, from + step - 1);
        const r = await rpc("eth_getLogs", [{ topics: [topic, pad(wallet)], fromBlock: "0x" + from.toString(16), toBlock: "0x" + to.toString(16) }]);
        if (r?.error) {
          lastErr = String(r.error.message ?? r.error.code).slice(0, 80);
          const hinted = Number(String(r.error.message ?? "").match(/(\d[\d,]*) (?:block )?range/)?.[1]?.replace(/,/g, ""));
          step = hinted > 0 && hinted < step ? hinted : Math.floor(step / 4);
          if (step < 1000) return { error: lastErr };
          continue;
        }
        out.push(...(r.result ?? []));
        from = to + 1;
      }
    }
    return { logs: out, source: "rpc" };
  }

  /** chain: "robinhood" | "base" | … (whatever rpcFor knows). */
  async function audit(wallet, chain) {
    const raw = rpcFor(chain);
    if (!raw) return { error: `no RPC for ${chain}` };
    const rpc = patient(raw);
    const owner = wallet.toLowerCase();
    const got = (await explorerLogs(chain, owner)) ?? (await logs(rpc, owner));
    if (got.error) return { error: `couldn't read the approval history (explorer unavailable, and the RPC says: ${got.error})` };
    const grants = latestGrants(got.logs).sort((a, b) => b.block - a.block); // newest first
    const live = [];
    await inPool(grants.slice(0, 80), 6, async (g) => {
      const sel = g.kind === "erc20" ? "0xdd62ed3e" : "0xe985e9c5";
      const r = await rpc("eth_call", [{ to: g.token, data: sel + pad(owner).slice(2) + pad(g.spender).slice(2) }, "latest"]);
      const readable = typeof r?.result === "string" && r.result.length >= 66;
      if (!readable) {
        // can't read the current state: report what was granted rather than silently dropping it
        if (g.kind === "all" || (g.granted ?? 0n) > 0n) live.push({ ...g, amount: g.granted ?? 0n, unread: true });
        return;
      }
      const v = BigInt(r.result.slice(0, 66));
      if (g.kind === "erc20" && v > 0n) live.push({ ...g, amount: v });
      if (g.kind === "all" && v === 1n) live.push(g);
    });
    const meta = new Map();
    const symbol = async (token) => {
      if (meta.has(token)) return meta.get(token);
      const [s, d] = [await rpc("eth_call", [{ to: token, data: "0x95d89b41" }, "latest"]), await rpc("eth_call", [{ to: token, data: "0x313ce567" }, "latest"])];
      let sym = null;
      try { const h = String(s?.result ?? "").slice(2); if (h.length >= 192) sym = new TextDecoder().decode(Uint8Array.from(h.slice(128, 128 + 2 * parseInt(h.slice(64, 128), 16)).match(/../g).map((b) => parseInt(b, 16)))); } catch {}
      let dec = null; try { dec = Number(BigInt(d?.result)); } catch {}
      const v = { symbol: sym && /^[\x20-\x7e]{1,16}$/.test(sym) ? sym : null, decimals: dec !== null && dec <= 36 ? dec : null };
      meta.set(token, v);
      return v;
    };
    const codeCache = new Map();
    const isContract = async (a) => {
      if (codeCache.has(a)) return codeCache.get(a);
      const c = (await rpc("eth_getCode", [a, "latest"]))?.result;
      const v = typeof c === "string" ? c !== "0x" && !c.toLowerCase().startsWith("0xef0100") : null;
      codeCache.set(a, v);
      return v;
    };
    const repCache = new Map();
    const flaggedFor = (a) => { if (!repCache.has(a)) repCache.set(a, reputation ? reputation(a).catch(() => []) : Promise.resolve([])); return repCache.get(a); };
    const out = [];
    await inPool(live, 6, async (g) => { await symbol(g.token); await isContract(g.spender); await flaggedFor(g.spender); }); // warm the caches in parallel
    for (const g of live) {
      const m = await symbol(g.token);
      const spenderIsContract = await isContract(g.spender);
      const flagged = await flaggedFor(g.spender);
      const risk = grantRisk({ ...g, spenderIsContract, spenderLabel: known[g.spender] ?? null, flagged });
      if (g.unread) risk.why.push("current allowance unreadable right now; this is the amount last granted");
      const amount = g.kind === "all" ? "ALL" : g.amount >= UNLIMITED ? "UNLIMITED"
        : m.decimals === null ? g.amount.toString() : (Number(g.amount) / 10 ** m.decimals).toLocaleString("en-US", { maximumFractionDigits: 4 });
      out.push({ token: g.token, symbol: m.symbol, spender: g.spender, spenderLabel: known[g.spender] ?? null, kind: g.kind, amount, grantedAtBlock: g.block, risk: risk.level, why: risk.why, revoke: risk.level === "low" ? null : revokeTx(g, owner) });
    }
    const order = { critical: 0, high: 1, medium: 2, low: 3 };
    out.sort((a, b) => order[a.risk] - order[b.risk]);
    return { wallet: owner, chain, historySource: got.source ?? "rpc", scannedGrants: grants.length, live: out.length, approvals: out };
  }
  return { audit };
}
return { latestGrants, grantRisk, revokeTx, KNOWN_SPENDERS, EXPLORERS, makeApprovals };
})();
// ── END bundle ──

const BAD = ["phishing_activities", "stealing_attack", "blacklist_doubt", "cybercrime", "money_laundering", "honeypot_related_address", "fake_kyc", "sanctioned", "financial_crime", "fake_token"];

export default async function handler(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const wallet = (url.searchParams.get("wallet") ?? url.searchParams.get("address") ?? "").trim().toLowerCase();
  const chain = (url.searchParams.get("chain") ?? "robinhood").toLowerCase();
  if (!/^0x[0-9a-f]{40}$/.test(wallet)) return bad(400, "invalid_wallet", "Pass ?wallet=0x…");
  if (!RPCS[chain]) return bad(400, "unsupported_chain", `Supported: ${Object.keys(RPCS).join(", ")}`);
  const rpcFor = (c: string) => async (method: string, params: unknown[]) => (await http(RPCS[c], { jsonrpc: "2.0", id: 1, method, params })).json ?? {};
  const reputation = async (a: string) => {
    const r = await http(`https://api.gopluslabs.io/api/v1/address_security/${a}?chain_id=${GOPLUS_ID[chain]}`);
    const x = r.json?.result ?? {};
    return BAD.filter((k) => x[k] === "1" || x[k] === 1).map((k) => k.replace(/_/g, " "));
  };
  const audit = __approvals.makeApprovals({ rpcFor, http, known: KNOWN, reputation }).audit(wallet, chain);
  const r: any = await Promise.race([audit, new Promise((res) => setTimeout(() => res(null), 25000))]);
  if (!r) return bad(504, "scan_timeout", "The chain was too slow to scan. You were not charged.");
  if (r.error) return bad(502, "scan_unavailable", `${r.error}. You were not charged.`);
  return Response.json({ ...r, worthRevoking: r.approvals.filter((x: any) => x.risk !== "low").length, checkedAt: new Date().toISOString(), disclaimer: DISCLAIMER });
}
